import Head from "next/head";
import { Inter } from "@next/font/google";
import { useContext } from "react";
import Modal from "@/Components/Modal";
import { ModalContext } from "@/Context/ModalContext";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

interface HomeProps {}

const Home: React.FC<HomeProps> = () => {
  const { InfoCoursessArr } = useContext<any>(ModalContext);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full p-5 h-screen bg-slate-300">
        <h1 className="text-xl font-bold mb-8">Курсы</h1>
        <div className="grid grid-cols-4 gap-5">
          {InfoCoursessArr.map((item: any) => (
            <div key={item.id} className="p-3 border-2 rounded-lg bg-white">
              <h1 className="text-lg font-semibold mb-4">{item.courses}</h1>
              <p>
                Курс предназначен для тех кто не уверен с чего начать свой путь
                в IT. Также курс идеально подойдет для неуверенных пользователей
                ПК. Во время курса мы затронем несколько программ по работе с
                документами и фотографиями: Google Docs, Google Sheets, Adobe
                Photoshop и графический редактор Figma.
              </p>
              <Link href={"./coursess/" + item.id}>
                <div className="p-2 border cursor-pointer rounded-full w-1/2 bg-[#f55302] text-white container mx-auto mt-4 flex justify-center">
                  <p>Посмотреть</p>
                </div>
              </Link>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
